version: '3.1'
services:
        database:
                image: "postgres" # use latest official postgres version
                container_name: "postgresql"
                restart: always
                env_file:
                        - database.env # configure postgres
                volumes:
                        - "./postgres/data:/var/lib/postgresql/data/:delegated" # persist data even if container shuts down
                ports:
                        - 5432:5432
